#!/bin/sh

#$ -N Particles
#$ -cwd
#$ -S /bin/sh
#$ -pe threads 48


path="/tmp/zberardo" #where the temporary files will go
home="/data/cosc462web/zberardo/parallelProg14" #the main directory
timesteps=1200;
threads=192;
deltaT=0.006; #change in time
numberofParticles=1000;
color=1 #0 for grayscale and 1 for color

#Loads ffmpeg on the newton cluster
module load ffmpeg

##### Change is not needed BELOW ######

input="particle.01.data" #initial particles created
pgmprefix="image"
dataprefix="timestep"
mkdir $path 2> /dev/null
$home/test/particlemaker $numberofParticles
cp $home/test/$input $path
echo "Particles have been Created"
echo "Processing Started"
$home/src/particleSimulator-omp input $path/$input dt $deltaT numSteps $timesteps output $path/$dataprefix threads $threads time 0
echo "Processing Done"
echo "Creating the Images"
for((i = 0; i < $timesteps; i++))
do {
	inputfile=$path/$dataprefix.$i.txt
	if [ $color -eq 1 ]
	then
		outputfile=$path/$pgmprefix.$i.ppm
		($home/src/particleToPpm input $inputfile xmin -1 xmax 1 ymin -1 ymax 1 xres 1280 yres 720 output $outputfile) &
	else
		outputfile=$path/$pgmprefix.$i.pgm
		$home/src/particleToPgm input $inputfile xmin -1 xmax 1 ymin -1 ymax 1 xres 1280 yres 720 output $outputfile
	fi

}
done
echo "Multiplexing Video"
rm -f $path/movie.mov
if [ $color -eq 1 ]
then
	ffmpeg -r 25 -sameq -i $path/$pgmprefix.%d.ppm $path/movie.mov 
else
	ffmpeg -r 25 -i $path/$pgmprefix.%d.pgm $path/movie.mov 
fi 
cp $path/movie.mov $home
echo "Simulation is done"
echo "Your movie is in $home"
#open movie.mov
#rm -f *.pgm
#rm -f $dataprefix*.txt
